"""
AI Appraisal & Asset Review service.

Wraps the Anthropic (Claude) API to power two product features:

  1. Automated Appraisal — an instant AI-generated value estimate for an asset,
     returning all 9 Section-10 fields: estimated value, confidence, appraisal
     summary, key value drivers, risk factors, missing information, recommended
     documents, suggested next step, and whether a professional appraisal is needed.
     This is explicitly NOT a certified appraisal; every result carries a disclaimer.
  2. AI Asset Review — an advisory accept/reject decision based on the asset's
     details and the supporting documents the user has uploaded.

Both use Claude with structured outputs (JSON schema) so the response is always
machine-parseable — no free-text parsing. The model and API key are read from
settings; if AI is disabled or unconfigured the caller gets a clean 503.
"""
import json
from typing import Any, Dict, List, Optional

from app.config import settings
from app.core.exceptions import ServiceUnavailableException
from app.utils.logger import logger

AUTOMATED_APPRAISAL_DISCLAIMER = (
    "Estimated value generated by the platform based on available data. "
    "This is not a certified professional appraisal or a guaranteed sale price."
)

_MAX_TOKENS = 4000

# ---- Structured output schemas -------------------------------------------------

_APPRAISAL_SCHEMA: Dict[str, Any] = {
    "type": "object",
    "properties": {
        "estimated_value": {
            "type": "number",
            "description": "Single best-estimate market value in the asset's currency.",
        },
        "value_range_low": {
            "type": "number",
            "description": "Low end of a plausible value range.",
        },
        "value_range_high": {
            "type": "number",
            "description": "High end of a plausible value range.",
        },
        "confidence": {
            "type": "string",
            "enum": ["low", "medium", "high"],
            "description": (
                "Confidence in the estimate given the data available. "
                "Use 'low' when key details are missing; 'high' when data is complete and comparable sales exist."
            ),
        },
        "appraisal_summary": {
            "type": "string",
            "description": "2-4 sentence summary of the appraisal finding and key reasoning.",
        },
        "key_value_drivers": {
            "type": "array",
            "items": {"type": "string"},
            "description": "Top factors that positively support the estimated value (e.g. brand, rarity, condition).",
        },
        "risk_factors": {
            "type": "array",
            "items": {"type": "string"},
            "description": "Factors that could reduce value or introduce uncertainty.",
        },
        "missing_information": {
            "type": "array",
            "items": {"type": "string"},
            "description": (
                "Specific data fields or details that are absent and would improve estimate accuracy. "
                "Empty array if all important details are present."
            ),
        },
        "recommended_documents": {
            "type": "array",
            "items": {"type": "string"},
            "description": "Documents that would strengthen the appraisal (e.g. purchase receipt, authentication certificate).",
        },
        "suggested_next_step": {
            "type": "string",
            "description": "Actionable recommendation for the asset owner after this appraisal.",
        },
        "professional_appraisal_needed": {
            "type": "boolean",
            "description": (
                "True when the asset type, value range, or missing data makes a certified "
                "professional appraisal strongly advisable."
            ),
        },
    },
    "required": [
        "estimated_value",
        "value_range_low",
        "value_range_high",
        "confidence",
        "appraisal_summary",
        "key_value_drivers",
        "risk_factors",
        "missing_information",
        "recommended_documents",
        "suggested_next_step",
        "professional_appraisal_needed",
    ],
    "additionalProperties": False,
}

_REVIEW_SCHEMA: Dict[str, Any] = {
    "type": "object",
    "properties": {
        "decision": {
            "type": "string",
            "enum": ["approved", "rejected", "needs_review"],
            "description": "approved = looks legitimate and complete; rejected = clear problem; needs_review = a human should look.",
        },
        "reason": {"type": "string", "description": "Short explanation of the decision."},
        "flags": {
            "type": "array",
            "items": {"type": "string"},
            "description": "Specific concerns, missing documents, or inconsistencies. Empty if none.",
        },
    },
    "required": ["decision", "reason", "flags"],
    "additionalProperties": False,
}

_APPRAISAL_SYSTEM_BASE = (
    "You are an expert asset valuation specialist. Given an asset's details, produce a "
    "comprehensive AI appraisal covering estimated market value, confidence level, summary, "
    "key value drivers, risk factors, missing information, recommended documents, a suggested "
    "next step, and whether a professional appraisal is needed. "
    "This is an approximate, automated estimate for guidance only — never claim certainty or "
    "present it as a certified appraisal. "
    "If data is thin, still produce an estimate but set confidence to 'low' and list the "
    "missing fields in missing_information — do NOT refuse to estimate."
)

_REVIEW_SYSTEM = (
    "You are an asset verification assistant. Given an asset's details and the list "
    "of supporting documents the owner has provided, decide whether the asset record "
    "appears legitimate and sufficiently documented. Approve when details are "
    "coherent and supporting documents are present; reject on clear inconsistencies "
    "or obviously invalid data; choose needs_review when a human should make the "
    "final call. Be conservative — when unsure, prefer needs_review over rejected."
)

# ---- Asset-type-specific appraisal guidance ------------------------------------

_CATEGORY_GUIDANCE: Dict[str, str] = {
    "real estate": (
        "Focus on: location (city/neighbourhood/country), property type, square footage/area, "
        "number of bedrooms and bathrooms, year built, lot size, condition, recent comparable "
        "sales in the area, local real estate market conditions, and any renovation or "
        "structural issues. For commercial property, note occupancy and rental income if provided."
    ),
    "jewelry": (
        "Focus on: material purity (gold karat, platinum grade, silver purity), gemstone details "
        "(type, carat weight, cut, colour, clarity, origin), brand/maker, age/period, condition, "
        "authentication certificates, hallmarks, and recent auction/retail comparables. "
        "Note if stones are certified by GIA, IGI, or similar."
    ),
    "watch": (
        "Focus on: brand, model name, reference number, movement type (mechanical/quartz), "
        "case material, case size, year of manufacture, condition (case, dial, bracelet/strap), "
        "presence of original box and papers, service history, and recent auction results for "
        "this specific reference."
    ),
    "yacht": (
        "Focus on: vessel name, manufacturer/builder, year built, LOA (length overall), beam, "
        "draft, engine hours, engine make/model, hull material, current location/marina, "
        "recent maintenance/survey records, equipment inventory, and current marine market "
        "conditions for this vessel class."
    ),
    "crypto": (
        "Focus on: cryptocurrency name and ticker symbol, quantity held, and current market "
        "price. Note that crypto values are highly volatile — widen the value range accordingly "
        "and set confidence to low/medium unless quantity and ticker are confirmed. "
        "Do not guess current prices; use the current_value field as the reference price if provided."
    ),
    "art": (
        "Focus on: artist name and reputation, title, medium (oil/watercolour/sculpture/print), "
        "dimensions, year created, provenance (ownership history), exhibition history, condition "
        "report, authentication documentation, and recent auction results for comparable works "
        "by this artist."
    ),
    "wine": (
        "Focus on: producer/château, vintage year, appellation/region, grape variety, bottle "
        "format (750ml/magnum/etc.), quantity, storage conditions (temperature/humidity/cellar), "
        "label/cork condition, and recent market prices from wine exchanges."
    ),
    "vehicle": (
        "Focus on: make, model, year, variant/trim, mileage/odometer, engine type, transmission, "
        "colour, condition (exterior/interior/mechanical), service history completeness, accident "
        "history, country/region of registration, and current market comparables (e.g. similar "
        "listings or recent auction results)."
    ),
    "collectible": (
        "Focus on: item type, manufacturer/publisher, year, edition/variant, condition using "
        "standard grading (e.g. Mint/Near Mint/Fine), rarity, provenance, completeness "
        "(original packaging, accessories, documentation), and recent sales of comparable items."
    ),
    "private equity": (
        "Focus on: company name, industry, stage (seed/Series A/growth/pre-IPO), last valuation "
        "round details, ownership percentage, revenue/EBITDA if disclosed, comparables in the "
        "sector, and liquidity constraints. Note that private equity values are highly illiquid "
        "and uncertain."
    ),
    "antique": (
        "Focus on: item category, period/era, origin/country, maker or attribution, material, "
        "dimensions, condition (patina, restoration, damage), provenance, and recent auction "
        "results for comparable antiques."
    ),
}


def _get_category_guidance(category_name: Optional[str], category_group: Optional[str]) -> str:
    """Return asset-type-specific appraisal instructions, or an empty string if none match."""
    search_terms = []
    if category_name:
        search_terms.append(category_name.lower())
    if category_group:
        search_terms.append(category_group.lower())

    for term in search_terms:
        for key, guidance in _CATEGORY_GUIDANCE.items():
            if key in term or term in key:
                return f"\n\nCategory-specific guidance for {category_name or category_group}:\n{guidance}"
    return ""


# ---- Internal helpers ----------------------------------------------------------

def is_ai_enabled() -> bool:
    """True when AI features are switched on and an API key is configured."""
    return bool(settings.AI_FEATURES_ENABLED and settings.ANTHROPIC_API_KEY)


def _get_client():
    """Lazily construct the async Anthropic client, or raise a clean 503."""
    if not is_ai_enabled():
        raise ServiceUnavailableException(
            "AI features are not configured. Set ANTHROPIC_API_KEY and AI_FEATURES_ENABLED."
        )
    try:
        from anthropic import AsyncAnthropic
    except ImportError as exc:  # pragma: no cover
        logger.error(f"anthropic SDK not installed: {exc}")
        raise ServiceUnavailableException("AI dependency is not installed on the server.")
    return AsyncAnthropic(api_key=settings.ANTHROPIC_API_KEY)


async def _call_claude(system: str, user_prompt: str, schema: Dict[str, Any]) -> Dict[str, Any]:
    """Call Claude with a JSON-schema-constrained response and return the parsed dict."""
    client = _get_client()
    try:
        response = await client.messages.create(
            model=settings.AI_MODEL,
            max_tokens=_MAX_TOKENS,
            thinking={"type": "adaptive"},
            system=system,
            messages=[{"role": "user", "content": user_prompt}],
            output_config={"format": {"type": "json_schema", "schema": schema}},
        )
    except ServiceUnavailableException:
        raise
    except Exception as exc:
        status_code = getattr(exc, "status_code", None)
        request_id = getattr(exc, "request_id", None)
        logger.error(f"AI request failed (status={status_code}, request_id={request_id}): {exc}")
        if status_code in (401, 403):
            raise ServiceUnavailableException(
                "AI authentication failed: the ANTHROPIC_API_KEY is invalid or not authorized. "
                "Set a valid key in the server's .env and restart."
            )
        if status_code == 404:
            raise ServiceUnavailableException(
                f"AI model '{settings.AI_MODEL}' is not available for this API key."
            )
        if status_code == 400:
            raise ServiceUnavailableException(f"AI request was rejected: {exc}")
        raise ServiceUnavailableException("The AI service is temporarily unavailable. Please try again.")

    text = next((b.text for b in response.content if getattr(b, "type", None) == "text"), None)
    if not text:
        logger.error("AI response contained no text block")
        raise ServiceUnavailableException("The AI service returned an empty response. Please try again.")
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        logger.error(f"AI response was not valid JSON: {exc}; raw={text[:500]}")
        raise ServiceUnavailableException("The AI service returned an unexpected response. Please try again.")


def _format_asset(asset_context: Dict[str, Any]) -> str:
    """Render the asset dict as a readable block for the prompt."""
    lines = []
    for key, value in asset_context.items():
        if value in (None, "", [], {}):
            continue
        lines.append(f"- {key}: {value}")
    return "\n".join(lines) if lines else "- (no details provided)"


# ---- Public API ----------------------------------------------------------------

async def generate_automated_appraisal(asset_context: Dict[str, Any]) -> Dict[str, Any]:
    """
    Produce an AI appraisal for an asset returning all Section-10 fields.

    `asset_context` must include standard asset fields (name, category, condition,
    currency, purchase_price, current_value, specifications, etc.) plus optionally
    `category_name` and `category_group` for type-specific guidance.

    Option A behaviour: always produces an estimate. If data is thin, confidence is
    set to 'low' and missing_information lists what's absent.

    Returns a dict with all schema fields plus `currency`, `disclaimer`, and `model`.
    """
    currency = asset_context.get("currency") or "USD"
    category_name = asset_context.get("category_name")
    category_group = asset_context.get("category_group")

    category_guidance = _get_category_guidance(category_name, category_group)
    system_prompt = _APPRAISAL_SYSTEM_BASE + category_guidance

    prompt = (
        f"Produce a full appraisal for this asset. All monetary values are in {currency}.\n\n"
        f"Asset details:\n{_format_asset(asset_context)}"
    )
    result = await _call_claude(system_prompt, prompt, _APPRAISAL_SCHEMA)
    result["currency"] = currency
    result["disclaimer"] = AUTOMATED_APPRAISAL_DISCLAIMER
    result["model"] = settings.AI_MODEL
    return result


async def review_asset(
    asset_context: Dict[str, Any],
    documents: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    """
    Produce an advisory accept/reject decision for an asset.

    Returns a dict: decision, reason, flags, model.
    """
    documents = documents or []
    if documents:
        doc_lines = "\n".join(
            f"- {d.get('document_type') or 'Document'}: {d.get('name') or d.get('file_name') or 'unnamed'}"
            for d in documents
        )
    else:
        doc_lines = "- (no supporting documents uploaded)"

    prompt = (
        f"Review this asset record and its supporting documents.\n\n"
        f"Asset details:\n{_format_asset(asset_context)}\n\n"
        f"Supporting documents:\n{doc_lines}"
    )
    result = await _call_claude(_REVIEW_SYSTEM, prompt, _REVIEW_SCHEMA)
    result["model"] = settings.AI_MODEL
    return result
