"""
AI Appraisal & Asset Review service.

Wraps the Anthropic (Claude) API to power two product features:

  1. Automated Appraisal — an instant AI-generated value estimate for an asset.
     This is explicitly NOT a certified appraisal; every result carries a
     disclaimer to that effect.
  2. AI Asset Review — an advisory accept/reject decision based on the asset's
     details and the supporting documents the user has uploaded.

Both use Claude with structured outputs (JSON schema) so the response is always
machine-parseable — no free-text parsing. The model and API key are read from
settings; if AI is disabled or unconfigured the caller gets a clean 503.
"""
import json
from typing import Any, Dict, List, Optional

from app.config import settings
from app.core.exceptions import ServiceUnavailableException
from app.utils.logger import logger

# Shown verbatim on every automated appraisal result. Mirrors the product
# requirement: an estimate, not a guaranteed sale price or certified appraisal.
AUTOMATED_APPRAISAL_DISCLAIMER = (
    "Estimated value generated by the platform based on available data. "
    "This is not a certified professional appraisal or a guaranteed sale price."
)

_MAX_TOKENS = 2000

# ---- Structured output schemas -------------------------------------------------

_APPRAISAL_SCHEMA: Dict[str, Any] = {
    "type": "object",
    "properties": {
        "estimated_value": {"type": "number", "description": "Single best-estimate value in the asset's currency."},
        "value_range_low": {"type": "number", "description": "Low end of a plausible value range."},
        "value_range_high": {"type": "number", "description": "High end of a plausible value range."},
        "confidence": {
            "type": "string",
            "enum": ["low", "medium", "high"],
            "description": "Confidence in the estimate given the data available.",
        },
        "reasoning": {"type": "string", "description": "Concise explanation of how the estimate was derived."},
    },
    "required": ["estimated_value", "value_range_low", "value_range_high", "confidence", "reasoning"],
    "additionalProperties": False,
}

_REVIEW_SCHEMA: Dict[str, Any] = {
    "type": "object",
    "properties": {
        "decision": {
            "type": "string",
            "enum": ["approved", "rejected", "needs_review"],
            "description": "approved = looks legitimate and complete; rejected = clear problem; needs_review = a human should look.",
        },
        "reason": {"type": "string", "description": "Short explanation of the decision."},
        "flags": {
            "type": "array",
            "items": {"type": "string"},
            "description": "Specific concerns, missing documents, or inconsistencies. Empty if none.",
        },
    },
    "required": ["decision", "reason", "flags"],
    "additionalProperties": False,
}

_APPRAISAL_SYSTEM = (
    "You are an asset valuation assistant. Given an asset's details, produce an "
    "estimated market value and a plausible value range using the asset type, "
    "condition, purchase price, specifications, and any comparable market knowledge "
    "you have. This is an approximate, automated estimate for guidance only — never "
    "claim certainty or present it as a certified appraisal. If data is thin, widen "
    "the range and set confidence to 'low'."
)

_REVIEW_SYSTEM = (
    "You are an asset verification assistant. Given an asset's details and the list "
    "of supporting documents the owner has provided, decide whether the asset record "
    "appears legitimate and sufficiently documented. Approve when details are "
    "coherent and supporting documents are present; reject on clear inconsistencies "
    "or obviously invalid data; choose needs_review when a human should make the "
    "final call. Be conservative — when unsure, prefer needs_review over rejected."
)


def is_ai_enabled() -> bool:
    """True when AI features are switched on and an API key is configured."""
    return bool(settings.AI_FEATURES_ENABLED and settings.ANTHROPIC_API_KEY)


def _get_client():
    """Lazily construct the async Anthropic client, or raise a clean 503."""
    if not is_ai_enabled():
        raise ServiceUnavailableException(
            "AI features are not configured. Set ANTHROPIC_API_KEY and AI_FEATURES_ENABLED."
        )
    try:
        from anthropic import AsyncAnthropic
    except ImportError as exc:  # pragma: no cover - dependency missing
        logger.error(f"anthropic SDK not installed: {exc}")
        raise ServiceUnavailableException("AI dependency is not installed on the server.")
    return AsyncAnthropic(api_key=settings.ANTHROPIC_API_KEY)


async def _call_claude(system: str, user_prompt: str, schema: Dict[str, Any]) -> Dict[str, Any]:
    """Call Claude with a JSON-schema-constrained response and return the parsed dict."""
    client = _get_client()
    try:
        response = await client.messages.create(
            model=settings.AI_MODEL,
            max_tokens=_MAX_TOKENS,
            thinking={"type": "adaptive"},
            system=system,
            messages=[{"role": "user", "content": user_prompt}],
            output_config={"format": {"type": "json_schema", "schema": schema}},
        )
    except ServiceUnavailableException:
        raise
    except Exception as exc:  # anthropic API / network errors
        status_code = getattr(exc, "status_code", None)
        request_id = getattr(exc, "request_id", None)
        logger.error(f"AI request failed (status={status_code}, request_id={request_id}): {exc}")
        # Configuration errors are not transient — say so clearly instead of "try again".
        if status_code in (401, 403):
            raise ServiceUnavailableException(
                "AI authentication failed: the ANTHROPIC_API_KEY is invalid or not authorized. "
                "Set a valid key in the server's .env and restart."
            )
        if status_code == 404:
            raise ServiceUnavailableException(
                f"AI model '{settings.AI_MODEL}' is not available for this API key."
            )
        if status_code == 400:
            raise ServiceUnavailableException(f"AI request was rejected: {exc}")
        # Rate limits, 5xx, and network errors are genuinely transient.
        raise ServiceUnavailableException("The AI service is temporarily unavailable. Please try again.")

    # output_config.format guarantees the first text block is valid JSON for the schema.
    text = next((b.text for b in response.content if getattr(b, "type", None) == "text"), None)
    if not text:
        logger.error("AI response contained no text block")
        raise ServiceUnavailableException("The AI service returned an empty response. Please try again.")
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        logger.error(f"AI response was not valid JSON: {exc}; raw={text[:500]}")
        raise ServiceUnavailableException("The AI service returned an unexpected response. Please try again.")


def _format_asset(asset_context: Dict[str, Any]) -> str:
    """Render the asset dict as a readable block for the prompt."""
    lines = []
    for key, value in asset_context.items():
        if value in (None, "", [], {}):
            continue
        lines.append(f"- {key}: {value}")
    return "\n".join(lines) if lines else "- (no details provided)"


async def generate_automated_appraisal(asset_context: Dict[str, Any]) -> Dict[str, Any]:
    """
    Produce an instant AI value estimate for an asset.

    `asset_context` is a plain dict of the asset's fields (name, type, condition,
    currency, purchase_price, current_value, specifications, etc.).

    Returns a dict: estimated_value, value_range_low, value_range_high, currency,
    confidence, reasoning, disclaimer, model.
    """
    currency = asset_context.get("currency") or "USD"
    prompt = (
        f"Estimate the market value of this asset. All monetary values are in {currency}.\n\n"
        f"Asset details:\n{_format_asset(asset_context)}"
    )
    result = await _call_claude(_APPRAISAL_SYSTEM, prompt, _APPRAISAL_SCHEMA)
    result["currency"] = currency
    result["disclaimer"] = AUTOMATED_APPRAISAL_DISCLAIMER
    result["model"] = settings.AI_MODEL
    return result


async def review_asset(
    asset_context: Dict[str, Any],
    documents: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    """
    Produce an advisory accept/reject decision for an asset.

    `documents` is a list of dicts describing the supporting documents on file
    (e.g. {"name": ..., "document_type": ...}). The decision is advisory: callers
    record it but it does not, by itself, hide or block the asset.

    Returns a dict: decision, reason, flags, model.
    """
    documents = documents or []
    if documents:
        doc_lines = "\n".join(
            f"- {d.get('document_type') or 'Document'}: {d.get('name') or d.get('file_name') or 'unnamed'}"
            for d in documents
        )
    else:
        doc_lines = "- (no supporting documents uploaded)"

    prompt = (
        f"Review this asset record and its supporting documents.\n\n"
        f"Asset details:\n{_format_asset(asset_context)}\n\n"
        f"Supporting documents:\n{doc_lines}"
    )
    result = await _call_claude(_REVIEW_SYSTEM, prompt, _REVIEW_SCHEMA)
    result["model"] = settings.AI_MODEL
    return result
